[[main]]
none = "none"

[[main]]
name = "About"
pageRef = "/about-me"
identifier = "qFeYxRrNOQ"
weight = 1

[[main]]
name = "Now"
pageRef = "/now"
identifier = "PcXqW0vrLd"
weight = 2

[[main]]
name = "What I Use"
pageRef = "/what-i-use"
weight = 3

[[main]]
name = "üçÇ BookLeaf"
url = "https://bookleaf.dev"
identifier = "QHXpp452MW"
weight = 4

[[footer]]
none = "none"
